### ISSUE TITLE
Normalizer error

### ISSUE THREAD

**Issue by bartblast** [hrzndhrn/beam_file#11]
There's probably a bug in the normalizer, please see examples:

```
iex> BeamFile.elixir_quoted(Kernel.SpecialForms)
** (FunctionClauseError) no function clause matching in Keyword.fetch!/2    
    
    The following arguments were given to Keyword.fetch!/2:
    
        # 1
        {:args, [version: 0, line: 1517], nil}
    
        # 2
        :do
    
    Attempted function clauses (showing 1 out of 1):
    
        def fetch!(keywords, key) when is_list(keywords) and is_atom(key)
    
    (elixir 1.14.5) lib/keyword.ex:592: Keyword.fetch!/2
    (beam_file 0.5.1) lib/beam_file/normalizer.ex:100: BeamFile.Normalizer.normalize/1
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (beam_file 0.5.1) lib/beam_file/normalizer.ex:111: BeamFile.Normalizer.normalize/1
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (beam_file 0.5.1) lib/beam_file/normalizer.ex:111: BeamFile.Normalizer.normalize/1
    iex:3: (file)
```

```
iex> BeamFile.elixir_quoted(Credo.IssueMeta)
** (FunctionClauseError) no function clause matching in Keyword.fetch!/2    
    
    The following arguments were given to Keyword.fetch!/2:
    
        # 1
        {:check_params, [version: 1, line: 13], nil}
    
        # 2
        :do
    
    Attempted function clauses (showing 1 out of 1):
    
        def fetch!(keywords, key) when is_list(keywords) and is_atom(key)
    
    (elixir 1.14.5) lib/keyword.ex:592: Keyword.fetch!/2
    (beam_file 0.5.1) lib/beam_file/normalizer.ex:100: BeamFile.Normalizer.normalize/1
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (beam_file 0.5.1) lib/beam_file/normalizer.ex:111: BeamFile.Normalizer.normalize/1
    (elixir 1.14.5) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (beam_file 0.5.1) lib/beam_file/normalizer.ex:111: BeamFile.Normalizer.normalize/1
    (beam_file 0.5.1) lib/beam_file/normalizer.ex:63: BeamFile.Normalizer.normalize/1
    iex:3: (file)
```

**Comment by NickNeck** [comment]
Thanks for reporting. I will take a look.
